# Base configs
baseurl: "https://shadowluminous.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-218253360-1"

# UI configs
title: "Shadow Luminous Photography"
subtitle: "There is one thing that photography must contain, the humanity of the moment."
author: "Dhesin Moodley"
header:
 title: "Shadow Luminous"
 subtitle: "Photography"
footer:
 name: "Dhesin Justin Moodley"
 bio1: "I started out as a photographer with the urge to tell stories and give people new perspectives and ways of seeing the world."
 bio2: "Today I am a portrait photographer that appreciates the raw reality of everyday life, the fleeting beauty of these in-between moments, and I do my very best to take every picture with that in mind. I want my viewers to relate to my photographs through recognition and familiarity with the situations, the emotions, and the energy so much that they wonder if they are looking at a picture of someone they know."
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/ramswaroop"
  twitter: "https://www.twitter.com/ram__patra"
  instagram: "https://www.instagram.com/ram_patra"
  dribbble: "https://dribbble.com/rampatra"
  linkedin: "https://in.linkedin.com/in/ram-patra"
  github: "https://www.github.com/rampatra"
