# Base configs
baseurl: "https://shadowluminous.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-218253360-1"

# UI configs
title: "Shadow Luminous Photography"
subtitle: "There is one thing that photography must contain, the humanity of the moment."
author: "Dhesin Moodley"
header:
 title: "Shadow Luminous"
 subtitle: "Photography"
footer:
 name: "Dhesin Justin Moodley"
 bio1: "Dhesin Justin Moodley is a photographer based in KwaZulu-Natal focused on partnering with creatives and brands to showcase beautiful and thoughtfully crafted design, product, and space."
 bio2: "He once started out with the urge to tell stories and give people new perspectives and ways of seeing the world and has since evolved into one that is quite literally addicted to taking photos, for which there is no known cure, except to take more."
web_design: "AJ"
social_urls:
  #facebook: "https://www.facebook.com/ramswaroop"
  #twitter: "https://www.twitter.com/shadowluminous"
  instagram: "https://www.instagram.com/shadowluminous"
  #dribbble: "https://dribbble.com/rampatra"
  #linkedin: "https://in.linkedin.com/in/ram-patra"
  #github: "https://www.github.com/rampatra"
  # In the index file just replace instagram with the respective social media name for the link icons
